/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './daterangepicker.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
export class Wrapper_DaterangePickerComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DaterangePickerComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  subscription3:any;
  subscription4:any;
  subscription5:any;
  subscription6:any;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.DaterangePickerComponent(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
    (this.subscription3 && this.subscription3.unsubscribe());
    (this.subscription4 && this.subscription4.unsubscribe());
    (this.subscription5 && this.subscription5.unsubscribe());
    (this.subscription6 && this.subscription6.unsubscribe());
  }
  check_options(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.options = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean,emit3:boolean,emit4:boolean,emit5:boolean,emit6:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.selected.subscribe(_eventHandler.bind(view,'selected'))); }
    if (emit1) { (this.subscription1 = this.context.cancelDaterangepicker.subscribe(_eventHandler.bind(view,'cancelDaterangepicker'))); }
    if (emit2) { (this.subscription2 = this.context.applyDaterangepicker.subscribe(_eventHandler.bind(view,'applyDaterangepicker'))); }
    if (emit3) { (this.subscription3 = this.context.hideCalendarDaterangepicker.subscribe(_eventHandler.bind(view,'hideCalendarDaterangepicker'))); }
    if (emit4) { (this.subscription4 = this.context.showCalendarDaterangepicker.subscribe(_eventHandler.bind(view,'showCalendarDaterangepicker'))); }
    if (emit5) { (this.subscription5 = this.context.hideDaterangepicker.subscribe(_eventHandler.bind(view,'hideDaterangepicker'))); }
    if (emit6) { (this.subscription6 = this.context.showDaterangepicker.subscribe(_eventHandler.bind(view,'showDaterangepicker'))); }
  }
}