/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './daterangepicker.module';
import * as import2 from './config.service';
import * as import3 from '@angular/core/src/di/injector';
class DaterangepickerInjector extends import0.NgModuleInjector<import1.Daterangepicker> {
  _Daterangepicker_0:import1.Daterangepicker;
  __DaterangepickerConfig_1:import2.DaterangepickerConfig;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _DaterangepickerConfig_1():import2.DaterangepickerConfig {
    if ((this.__DaterangepickerConfig_1 == null)) { (this.__DaterangepickerConfig_1 = new import2.DaterangepickerConfig()); }
    return this.__DaterangepickerConfig_1;
  }
  createInternal():import1.Daterangepicker {
    this._Daterangepicker_0 = new import1.Daterangepicker();
    return this._Daterangepicker_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Daterangepicker)) { return this._Daterangepicker_0; }
    if ((token === import2.DaterangepickerConfig)) { return this._DaterangepickerConfig_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DaterangepickerNgFactory:import0.NgModuleFactory<import1.Daterangepicker> = new import0.NgModuleFactory(DaterangepickerInjector,import1.Daterangepicker);